version: "3"
services:
    psql:
        image: postgres:12
        hostname: postgres
        env_file:
            - postgres.env
        volumes:
            - "postgres_data:/var/lib/postgresql/data/"
        ports:
            - "5434:5432"
        restart: unless-stopped

    main-service:
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - ./.env
        environment:
            - RUNNING_IN_DOCKER=true
        depends_on:
            - psql
        hostname: main-service
        working_dir: /root/
        volumes:
            - service_data:/go/src/github.com/armingodiz/web-project
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - default
        ports:
            - "3000:3000"

networks:
  default:
    external:
      name: web-project

volumes:
    postgres_data:
    service_data: